# Generated by Django 3.2.25 on 2024-09-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractrule',
            old_name='contract_id',
            new_name='contract',
        ),
        migrations.RenameField(
            model_name='customerplan',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customerplan',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='parkmovement',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
